export const Emoji = {
  overview: 'fluent-emoji-flat:smiling-face',
  records: 'fluent-emoji-flat:notebook',
  community: 'fluent-emoji-flat:people-hugging',
  care: 'fluent-emoji-flat:heart-hands',
  chat: 'fluent-emoji-flat:mobile-phone',
  escalation: 'fluent-emoji-flat:sos-button',
  history: 'fluent-emoji-flat:counterclockwise-arrows-button',
  profile: 'fluent-emoji-flat:bust-in-silhouette',
  psychologist: 'fluent-emoji-flat:health-worker',
  brain: 'fluent-emoji-flat:brain',
  sparkle: 'fluent-emoji-flat:sparkles',
  mood: 'fluent-emoji-flat:smiling-face',
  journal: 'fluent-emoji-flat:notebook',
  grounding: 'fluent-emoji-flat:wind-face',
  heatmap: 'fluent-emoji-flat:world-map',
  referral: 'fluent-emoji-flat:love-letter',
  medical: 'fluent-emoji-flat:medical-symbol',
  shield: 'fluent-emoji-flat:shield',
  picture: 'fluent-emoji-flat:framed-picture',
  purpleHeart: 'fluent-emoji-flat:purple-heart',
  whiteHeart: 'fluent-emoji-flat:white-heart',
  greenHeart: 'fluent-emoji-flat:green-heart',
  camera: 'fluent-emoji-flat:camera',
  happy: 'fluent-emoji-flat:grinning-face-with-big-eyes',
  calm: 'fluent-emoji-flat:relieved-face',
  neutral: 'fluent-emoji-flat:neutral-face',
  anxious: 'fluent-emoji-flat:anxious-face-with-sweat',
  sad: 'fluent-emoji-flat:downcast-face-with-sweat',
  distressed: 'fluent-emoji-flat:face-screaming-in-fear',
} as const

export const MoodEmoji: Record<string, string> = {
  HAPPY: Emoji.happy,
  CALM: Emoji.calm,
  NEUTRAL: Emoji.neutral,
  ANXIOUS: Emoji.anxious,
  SAD: Emoji.sad,
  DISTRESSED: Emoji.distressed,
}

export const MenuEmoji: Record<string, string> = {
  overview: Emoji.overview,
  records: Emoji.records,
  community: Emoji.community,
  care: Emoji.care,
  chat: Emoji.chat,
  history: Emoji.history,
  profile: Emoji.profile,
}
